[[SDPA]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73877c90749a23b9f72e642888650e9d031ee606"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SDPA.download]]
    sha256 = "1bc99406e5f835fa2de3e76d9acc9a1dbae99d35dda7513af62434f427b4fd19"
    url = "https://github.com/JuliaBinaryWrappers/SDPA_jll.jl/releases/download/SDPA-v7.3.8+1/SDPA.v7.3.8.aarch64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[SDPA]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "989ef6a8e45c3c8c27eb6a7d016185eb329d51c6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SDPA.download]]
    sha256 = "a067350e7937e32833a524312315aae64f82082e5c85013dab973519089b763e"
    url = "https://github.com/JuliaBinaryWrappers/SDPA_jll.jl/releases/download/SDPA-v7.3.8+1/SDPA.v7.3.8.armv7l-linux-gnueabihf-libgfortran4-cxx11.tar.gz"
[[SDPA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cdff6f76fdd32ad93cb99c5781ee53e671e526ae"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SDPA.download]]
    sha256 = "e435696b78e37e2cc613fd5e3ef3561532982398f2729f92948af94d5c26cf0c"
    url = "https://github.com/JuliaBinaryWrappers/SDPA_jll.jl/releases/download/SDPA-v7.3.8+1/SDPA.v7.3.8.i686-linux-gnu-libgfortran4-cxx11.tar.gz"
[[SDPA]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a49a4806d851314d22e0f829beb4b260969dd823"
libgfortran_version = "4.0.0"
os = "windows"

    [[SDPA.download]]
    sha256 = "9a12a5b57b7109dd7a75b8cd491c19f440cc5ce441fc92cef0e307000c2c6baf"
    url = "https://github.com/JuliaBinaryWrappers/SDPA_jll.jl/releases/download/SDPA-v7.3.8+1/SDPA.v7.3.8.i686-w64-mingw32-libgfortran4-cxx11.tar.gz"
[[SDPA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e23752a63bb17aa14d5751356e5a93c9cdef45b0"
libgfortran_version = "4.0.0"
os = "macos"

    [[SDPA.download]]
    sha256 = "af1b23250b802a6fd7222cb2f988c1b1421a710b1665d47b64505a346b4be560"
    url = "https://github.com/JuliaBinaryWrappers/SDPA_jll.jl/releases/download/SDPA-v7.3.8+1/SDPA.v7.3.8.x86_64-apple-darwin14-libgfortran4-cxx11.tar.gz"
[[SDPA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1439a9ff6d3ceb79ab3d4ccdcdc16e706c2adcdd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SDPA.download]]
    sha256 = "4e0929184de50ab0e248d9d8aa76f6a085e980c6929ecbe57bcad96a069ba037"
    url = "https://github.com/JuliaBinaryWrappers/SDPA_jll.jl/releases/download/SDPA-v7.3.8+1/SDPA.v7.3.8.x86_64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[SDPA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78ff099d03f503131e6b93e0c73feecb828153ab"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SDPA.download]]
    sha256 = "4a9e86194f5c60ef109e4becc25691a1ae546b542f9693c2ed88a01904d23ffa"
    url = "https://github.com/JuliaBinaryWrappers/SDPA_jll.jl/releases/download/SDPA-v7.3.8+1/SDPA.v7.3.8.x86_64-unknown-freebsd11.1-libgfortran4-cxx11.tar.gz"
[[SDPA]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d828329809333d4c6bb509394d54561d0212a6c"
libgfortran_version = "4.0.0"
os = "windows"

    [[SDPA.download]]
    sha256 = "7ffb5037a7a4fd30ff8c81839f2b11ccc96df9e4235580e04f2b71a2069d689e"
    url = "https://github.com/JuliaBinaryWrappers/SDPA_jll.jl/releases/download/SDPA-v7.3.8+1/SDPA.v7.3.8.x86_64-w64-mingw32-libgfortran4-cxx11.tar.gz"
